apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-secret-example
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: my-gcp-secret
    creationPolicy: Owner
  data:
    - secretKey: my-secret-key
      remoteRef:
        key: "esotest"