apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: nice-hydra-435514-e8
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: eso-gcp-credentials
            key: key.json