apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: nice-hydra-435514-e8
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: my-cluster       
          serviceAccountRef:
            name: team-a
